name: CMake Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build_linux_cpu:
    name: build_linux_cpu
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install OpenBLAS
        run: sudo apt-get install -y libopenblas-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_CUDA=OFF -DTEST_CUDA=OFF

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: cd ${{github.workspace}}/build && ctest

      - name: Demo
        run: cd ${{github.workspace}}/demo/bin && ./TinyTorch_demo

  build_linux_gpu:
    name: build_linux_gpu
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: cuda-toolkit
        uses: Jimver/cuda-toolkit@v0.2.22

      - name: Install OpenBLAS
        run: sudo apt-get install -y libopenblas-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_CUDA=ON -DTEST_CUDA=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        run: cd ${{github.workspace}}/build && ctest

      - name: Demo
        run: cd ${{github.workspace}}/demo/bin && ./TinyTorch_demo
